import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function POST(req: Request) {
    try {
        const { prompt } = await req.json()

        if (!prompt) {
            return NextResponse.json({ error: 'Prompt is required' }, { status: 400 })
        }

        const supabase = await createClient()

        // 1. Get the API key from settings
        const { data: settingsData } = await supabase
            .from('site_settings')
            .select('*')

        const settings = settingsData?.reduce((acc: any, curr) => {
            acc[curr.setting_key] = curr.setting_value
            return acc
        }, {})

        const apiKey = settings?.gemini_api_key
        if (!apiKey) {
            return NextResponse.json({ error: 'Gemini API key not configured in settings' }, { status: 400 })
        }

        // 2. Call Gemini for Image Generation
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [
                    {
                        parts: [{ text: prompt }]
                    }
                ],
                generationConfig: {
                    responseModalities: ["IMAGE"]
                }
            })
        })

        const data = await response.json()

        if (!response.ok) {
            console.error("Gemini API Error:", data);
            return NextResponse.json({ error: data.error?.message || 'Failed to generate image' }, { status: response.status })
        }

        // 3. Extract the image from the response
        // The image is usually returned in candidates[0].content.parts[0].inlineData.data (base64)
        const parts = data.candidates?.[0]?.content?.parts || []
        const imagePart = parts.find((p: any) => p.inlineData && p.inlineData.mimeType.startsWith('image/'))

        if (!imagePart) {
             // Fallback if they didn't return inlineData. Try gemini-2.5-flash-image specifically if the above fails.
             console.error("No image part found. Data:", JSON.stringify(data));
             return NextResponse.json({ error: 'No image was generated by the model. Make sure your key supports image generation.' }, { status: 500 })
        }

        const base64Image = imagePart.inlineData.data
        const mimeType = imagePart.inlineData.mimeType || 'image/jpeg'

        return NextResponse.json({ 
            base64: base64Image,
            mimeType: mimeType
        })

    } catch (error: any) {
        console.error('Image Generation Error:', error)
        return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 })
    }
}
